export const ENGLISH_WORDS = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "tell", "very", "every", "find", "here", "place", "show", "life", "know",
  "child", "many", "young", "work", "school", "system", "before", "right", "world", "local",
  "under", "social", "national", "state", "point", "government", "water", "home", "number", "group",
  "company", "woman", "business", "friend", "money", "study", "general", "game", "book", "hand",
  "different", "area", "family", "house", "room", "point", "end", "member", "law", "car",
  "city", "community", "name", "sentence", "line", "cause", "much", "mean", "before", "move",
  "right", "boy", "old", "too", "same", "she", "all", "there", "when", "up",
  "use", "your", "way", "about", "many", "then", "them", "write", "would", "like",
  "so", "these", "her", "long", "make", "thing", "see", "him", "two", "has",
  "look", "more", "day", "could", "go", "come", "did", "number", "sound", "no",
  "most", "people", "my", "over", "know", "water", "than", "call", "first", "who",
  "may", "down", "side", "been", "now", "find", "any", "new", "work", "part",
  "take", "get", "place", "made", "live", "where", "after", "back", "little", "only",
  "round", "man", "year", "came", "show", "every", "good", "me", "give", "our",
  "under", "name", "very", "through", "just", "form", "sentence", "great", "think", "say",
  "above", "across", "act", "active", "activity", "add", "afraid", "again", "against", "age",
  "ago", "agree", "air", "alone", "along", "already", "always", "amount", "ancient", "angry",
  "another", "answer", "anyone", "anything", "anytime", "appear", "apple", "arm", "around", "arrive",
  "art", "ask", "attack", "aunt", "autumn", "away", "baby", "bad", "bag", "ball",
  "banana", "band", "bank", "bar", "base", "basic", "bat", "bath", "beach", "bear",
  "beat", "beautiful", "beauty", "become", "bed", "bedroom", "beer", "began", "begin", "behind",
  "believe", "bell", "below", "beside", "best", "better", "between", "beyond", "bicycle", "big",
  "bill", "bird", "birth", "birthday", "bit", "bite", "black", "blank", "bleed", "blind",
  "block", "blood", "blow", "blue", "board", "boat", "body", "bone", "boot", "border",
  "born", "borrow", "boss", "both", "bottle", "bottom", "bought", "bowl", "box", "brain",
  "branch", "brave", "bread", "break", "breakfast", "breath", "breathe", "bridge", "bright", "bring",
  "broad", "broke", "broken", "brother", "brown", "brush", "building", "built", "burn", "bus",
  "bush", "busy", "butter", "buy", "cabin", "cage", "cake", "calm", "camera", "camp",
  "canal", "candle", "cap", "capital", "captain", "card", "care", "careful", "careless", "carry",
  "case", "cat", "catch", "caught", "cave", "cell", "cent", "center", "central", "century",
  "certain", "chain", "chair", "chance", "change", "character", "charge", "chart", "chase", "cheap",
  "cheese", "chemical", "chest", "chicken", "chief", "children", "chimney", "chin", "chips", "choice",
  "choose", "chose", "chosen", "church", "circle", "claim", "class", "clay", "clean", "clear",
  "clever", "click", "climb", "close", "cloth", "clothes", "cloud", "club", "coach", "coal",
  "coast", "coat", "code", "coffee", "cold", "collect", "college", "colony", "color", "column",
  "comb", "combination", "combine", "comfortable", "common", "compare", "compass", "complete", "condition", "congress",
  "connect", "consider", "consonant", "constant", "continent", "continue", "contrast", "control", "conversation", "cook",
  "cool", "copper", "copy", "corn", "corner", "correct", "cost", "cotton", "count", "country",
  "couple", "courage", "course", "court", "cover", "cow", "cowboy", "crack", "craft", "crash",
  "crawl", "crazy", "cream", "create", "creature", "crew", "cried", "crop", "cross", "crowd",
  "crown", "cry", "cup", "curious", "current", "curve", "custom", "cut", "cycle", "daily",
  "damage", "dance", "danger", "dangerous", "dark", "daughter", "dawn", "dead", "deal", "dear",
  "death", "decide", "decision", "deck", "declare", "deep", "deer", "defeat", "defend", "define",
  "degree", "delay", "delicate", "delight", "deliver", "demand", "department", "depend", "depth", "describe",
  "desert", "design", "desire", "desk", "detail", "determine", "develop", "device", "devote", "dial",
  "diameter", "die", "differ", "difference", "difficult", "dig", "dinner", "direct", "direction", "dirty",
  "discover", "discovery", "discuss", "discussion", "disease", "dish", "distance", "distant", "divide", "division",
  "doctor", "does", "dog", "doll", "dollar", "done", "donkey", "door", "double", "doubt",
  "dozen", "drag", "draw", "drawer", "drawing", "drawn", "dream", "dress", "drew", "dried",
  "drill", "drink", "drive", "driven", "driver", "driving", "drop", "dropped", "drove", "drown",
  "drum", "dry", "duck", "due", "dug", "dull", "during", "dust", "duty", "each",
  "eager", "ear", "early", "earn", "earth", "ease", "east", "easy", "eaten", "edge",
  "education", "effect", "effort", "egg", "eight", "either", "electric", "electricity", "element", "elephant",
  "eleven", "else", "empty", "enemy", "energy", "engine", "engineer", "enjoy", "enough", "enter",
  "entire", "entrance", "equal", "equation", "escape", "especially", "essay", "establish", "evening", "event",
  "ever", "everyone", "everything", "evidence", "exact", "examine", "example", "excellent", "except", "exchange",
  "excited", "excitement", "excuse", "exercise", "exist", "expect", "expense", "experience", "experiment", "explain",
  "explanation", "explore", "express", "expression", "eye", "face", "fact", "factor", "factory",
  "fade", "fail", "failure", "faint", "fair", "fairly", "fairy", "faith", "fall",
  "fallen", "famous", "fan", "fancy", "far", "farm", "farmer", "farther", "fashion",
  "fast", "fasten", "fat", "father", "fatigue", "fault", "favor", "favorite", "fear",
  "fearful", "feather", "feature", "fed", "feed", "feel", "feeling", "feet", "fell",
  "fellow", "felt", "fence", "few", "fewer", "fiber", "fiction", "field", "fierce",
  "fifth", "fifty", "fight", "fighter", "fighting", "figure", "fill", "film", "filter",
  "final", "finally", "fine", "finger", "finish", "fire", "fireplace", "firm", "fish",
  "fisherman", "fist", "fit", "five", "fix", "flag", "flat", "flavor", "flee",
  "flesh", "flew", "flight", "float", "flock", "flood", "floor", "flow", "flower",
  "flown", "fluid", "fly", "foam", "focus", "fog", "fold", "folks", "follow",
  "fond", "food", "fool", "foot", "football", "force", "foreign", "forest", "forget",
  "forgot", "forgotten", "fork", "formal", "former", "fort", "forth", "forty",
  "forward", "fought", "foul", "found", "foundation", "four", "fourth", "fox",
  "frame", "free", "freedom", "freeze", "freight", "french", "frequency", "frequent",
  "fresh", "friendly", "frighten", "frog", "front", "frost", "frown", "fruit",
  "fry", "fuel", "full", "fully", "fun", "function", "funny", "fur", "furniture",
  "further", "future", "gain", "garage", "garden", "gas", "gasoline", "gate",
  "gather", "gave", "gay", "gear", "generally", "gentle", "gentleman", "getting",
  "giant", "gift", "girl", "given", "giving", "glad", "glide", "gloom", "glory",
  "glove", "go", "goal", "goat", "god", "gold", "golden", "gone", "goose",
  "got", "govern", "governor", "grab", "grace", "grade", "gradual", "grain",
  "grand", "grandfather", "grandmother", "grant", "grass", "grave", "gray", "grease",
  "greatly", "green", "grew", "grey", "grid", "grief", "grind", "grip", "grocer",
  "grocery", "ground", "grove", "grow", "grown", "growth", "guard", "guess",
  "guest", "guide", "gulf", "gum", "gun", "habit", "had", "hair", "half",
  "halfway", "hall", "halo", "halt", "ham", "hammer", "handful", "handle",
  "handsome", "hang", "happen", "happy", "harbor", "hardly", "hardy", "harm",
  "harness", "harp", "harvest", "haste", "hasten", "hasty", "hat", "hate",
  "hatred", "haven", "having", "hawk", "hay", "head", "header", "heal",
  "health", "healthy", "heap", "hear", "heard", "hearing", "heart", "heat",
  "heater", "heaven", "heavy", "hebrew", "hectare", "heel", "height", "held",
  "helicopter", "hell", "hello", "helm", "helmet", "helpful", "hem", "hen",
  "herd", "hero", "hers", "herself", "hid", "hidden", "hide", "highly",
  "highway", "hill", "himself", "hind", "hinge", "hint", "hip", "hire",
  "history", "hit", "hive", "hoarse", "hobby", "hoe", "hog", "holder",
  "holding", "hole", "holiday", "hollow", "holy", "homestead", "honest", "honey",
  "honor", "hood", "hoof", "hook", "hoop", "hop", "hope", "hopeful",
  "horn", "horse", "rose", "hospital", "host", "hot", "hotel", "hour",
  "household", "housewife", "hover", "however", "howl", "hub", "huge",
  "hum", "human", "humble", "humor", "hundred", "hung", "hunt", "hunter",
  "hurry", "hurt", "husband", "hut"
];

export const INDONESIAN_WORDS = [
  "dan", "yang", "untuk", "dengan", "saya", "dia", "mereka", "kita", "anda", "tidak",
  "bisa", "ada", "pada", "dari", "ke", "dalam", "akan", "telah", "ini", "itu",
  "oleh", "sebagai", "karena", "atau", "tetapi", "juga", "sudah", "dapat", "sekarang", "hanya",
  "banyak", "orang", "hari", "tahun", "tahu", "baru", "satu", "dua", "tiga", "jalan",
  "kerja", "masuk", "keluar", "rumah", "anak", "ibu", "ayah", "teman", "waktu", "tempat",
  "buku", "tulis", "baca", "belajar", "sekolah", "negara", "pemerintah", "masyarakat", "kota", "desa",
  "air", "makan", "minum", "tidur", "bangun", "pagi", "siang", "sore", "malam", "bulan",
  "minggu", "jam", "menit", "detik", "cepat", "lambat", "bagus", "buruk", "besar", "kecil",
  "panjang", "pendek", "tinggi", "rendah", "jauh", "dekat", "luar", "dalam", "atas", "bawah",
  "tengah", "depan", "belakang", "kiri", "kanan", "tangan", "kaki", "kepala", "mata", "telinga",
  "hidung", "mulut", "gigi", "rambut", "hati", "jiwa", "hidup", "mati", "lahir", "tumbuh",
  "selalu", "sering", "kadang", "jarang", "pernah", "belum", "sedang", "selesai",
  "mulai", "berhenti", "kembali", "pergi", "datang", "tiba", "tinggal", "menjadi", "membuat", "melakukan",
  "melihat", "mendengar", "merasa", "memikirkan", "membawa", "mengambil", "memberi", "menerima", "mencari", "menemukan",
  "membantu", "menolong", "mengajar", "menulis", "membaca", "berbicara", "berkata", "bertanya", "menjawab", "memahami",
  "mengerti", "ingat", "lupa", "suka", "benci", "cinta", "takut", "berani", "marah",
  "senang", "sedih", "bahagia", "kecewa", "lelah", "capek", "sakit", "sehat", "kuat", "lemah",
  "bersih", "kotor", "mudah", "sulit", "susah", "murah", "mahal", "kaya", "miskin",
  "lama", "tua", "muda", "benar", "salah", "betul", "mungkin", "pasti", "tentu", "harus",
  "boleh", "perlu", "biasa", "semua", "setiap", "beberapa", "sebagian", "seluruh",
  "abang", "abu", "acara", "adalah", "adil", "agak", "agama", "agar", "agung", "ahli",
  "ajak", "ajar", "akar", "akhir", "akibat", "aksi", "aku", "alam", "alat", "album",
  "alasan", "aliran", "alis", "almarhum", "altar", "aman", "amat", "ambil", "angin", "angka",
  "angkatan", "anjing", "antar", "antara", "antrian", "apa", "apabila", "api", "apresiasi", "arah",
  "arsip", "arti", "artikel", "arus", "asam", "asap", "asing", "asli", "asal", "aspek",
  "aspirasi", "asrama", "asuransi", "aturan", "aurora", "awan", "awas", "ayam", "ayat",
  "badai", "badan", "badut", "bagai", "bagaimana", "bagian", "bahan", "bahas", "bahaya", "bahu",
  "baik", "baja", "bajak", "baju", "bakar", "bakat", "bakti", "balai", "balas", "balon",
  "balok", "bambu", "bandar", "banding", "bangsa", "banjir", "bantal", "bantu", "bapak", "barat",
  "baring", "baris", "basah", "basis", "batas", "batik", "batu", "batuk", "bau", "bawang",
  "bayar", "bayi", "bayang", "bebas", "beban", "bebek", "bekas", "bekerja", "bela",
  "belalang", "beli", "beliau", "bencana", "benda", "bendera", "bengkel", "benih", "beras",
  "berbagi", "berbuat", "berdiri", "beres", "berharga", "berita", "berjalan", "berkembang", "bermain", "bernasib",
  "berubah", "besi", "besok", "biar", "biaya", "bibir", "bicara", "biji", "bikin",
  "bilang", "bimbing", "bina", "binatang", "bingung", "biola", "bioskop", "biru", "bisik",
  "bisnis", "bintang", "bocah", "bohong", "bola", "bom", "boneka", "bosan", "botol",
  "buah", "buang", "bubur", "budaya", "bukti", "bulat", "bulu", "bumbu", "bumi",
  "bunga", "bungkus", "bunyi", "buru", "burung", "bus", "busur", "butuh", "cabang",
  "cabe", "cacing", "cahaya", "cair", "cakap", "calon", "campur", "candi", "cangkir",
  "cantik", "capai", "cara", "cari", "catat", "catatan", "catur", "cegah", "celana",
  "celah", "cerdas", "cerita", "cermin", "cipta", "ciri", "cita", "cium", "coba",
  "cocok", "cokelat", "contoh", "corak", "cuaca", "cuci", "cukup", "cuma", "curah",
  "curi", "dada", "daerah", "daftar", "daging", "dagu", "dahulu", "darat", "darurat",
  "datar", "daya", "debu", "delapan", "demi", "demikian", "denda", "dengar", "derajat",
  "desain", "desember", "dewan", "dewasa", "di", "diam", "didik", "dingin", "diri",
  "doa", "dokumen", "dorong", "dosa", "dosen", "duduk", "duga", "durian", "dusta",
  "dusun", "ember", "emas", "empuk", "enak", "enam", "enggan", "entah", "erat",
  "esok", "faedah", "fajar", "fase", "fikir", "fisik", "fitur", "formal", "forum",
  "foto", "fungsi", "gading", "gadis", "gagah", "gagasan", "gajah", "gaji", "gala",
  "gambar", "gampang", "ganjil", "garam", "garpu", "gaya", "gedung", "gejala", "gelang",
  "gelap", "gelar", "gelas", "gelembung", "geli", "gelombang", "gembira", "gempa", "gemuk",
  "genap", "gerak", "gereja", "gerbang", "getar", "gila", "giling", "gips", "gitar",
  "glamor", "global", "goa", "gondol", "goreng", "gores", "gosok", "gudang", "gugur",
  "gula", "guling", "gulung", "guna", "gunung", "guru", "habis", "hadap", "hadiah",
  "hadir", "hafal", "hujan", "hutan"
];

// Helper to generate a list of randomized words
export const generateWords = (count, language = 'english') => {
  const wordList = language === 'indonesian' ? INDONESIAN_WORDS : ENGLISH_WORDS;
  const result = [];
  for (let i = 0; i < count; i++) {
    const randomIndex = Math.floor(Math.random() * wordList.length);
    result.push(wordList[randomIndex]);
  }
  return result;
};
